### PR TITLE
[WIP] Add multilanguage support

### PR DESCRIPTION
**Pull request by Holzhaus**
This will add basic multilanguage support for the Jasper core and the individual plugins.

- [X] Make Jasper translatable
- [X] Add multilanguage support for STT plugins
- [X] Add multilanguage support for TTS plugins
- [x] Add multilanguage support for SpeechHandler plugins
- [X] Add `*.po` files for Jasper
- [x] Add `*.po` files for SpeechHandler plugins

Don't worry, a PR to integrate a better config system (that avoids all this `try/except` madness) will follow.

### CODE REVIEW

**Comment by grigi** [comment]
Hi, I did an experimental multi-language TTS engine here: https://github.com/grigi/talkey/

I had a quick look at some of the diffs here, and I would like to bring some things to your attention:
* eSpeak has a list of languages it deems good but only differentiates in the documentation. https://github.com/grigi/talkey/blob/master/talkey/engines/espeak.py#L17
* There is also a bug with some versions where the gender column is sometimes missing https://github.com/grigi/talkey/blob/master/talkey/engines/espeak.py#L83
* And it would be fantastic if you could add mbrola voice support, as for example the mbrola-en1 voice is fantastic. https://github.com/grigi/talkey/blob/master/talkey/engines/espeak.py#L96

Also, in that library I used the langid library to great effect to detect languages, it allowed me to let the engine choose the language based from a set of languages, and it works great. (With some caveats, if you want to support many languages, it is better to skew the results according to your preferences https://github.com/grigi/talkey/blob/master/talkey/tts.py#L105

I should have told this group about that library earlier, apologies for that.

**Comment by Holzhaus** [comment]
@grigi Thanks for your valuable feedback.

> eSpeak has a list of languages it deems good but only differentiates in the documentation.

Good to know. We'll add this to the documentation when this hits the master branch. (Since we don't have language auto-selection right now, we don't need to hardcode quality languages in our code.)

> There is also a bug with some versions where the gender column is sometimes missing

Could you point me to the bug report and/or post example output of the voices command in that case? I'd like to know how that'd look like to check if it breaks the parser code.

> And it would be fantastic if you could add mbrola voice support, as for example the mbrola-en1 voice is fantastic.

Doesn't that already work? It does for me (check out [Line 83](https://github.com/jasperproject/jasper-client/commit/e26ec13a7f54c740221b541d9ddf2b2a1890b27c#diff-7cc9b67622982d4874ff3c72e1beaae2R83)). If that doesn't work for you, could you please give me some details about the error you're getting?

> Also, in that library I used the langid library to great effect to detect languages, it allowed me to let the engine choose the language based from a set of languages, and it works great.

Hmm, I don't see the point of deducing the language from a given text if you already know what language that text is written in (i.e. the language the user configured in a config file).
Even if we allowed plugins to output text in another language than the configured language (i.e. for a Google Translator Plugin or something like that), the plugin would know which language it outputs and could pass in an additional parameter. This seems a lot less error-prone to me than guessing the language from text directly.

Thanks again!

**Comment by grigi** [comment]
Hi, thanks for listening to my rambling :-)

http://espeak.sourceforge.net/languages.html
Section 3.4 details the acceptable quality languages other than english. All the languages in 3.5 is considered unusable.

Newer eSpeak does this:
```
Pty Language Age/Gender VoiceName          File          Other Languages
 5  af             M  afrikaans            other/af      
 5  an             M  aragonese            europe/an     
 5  bg             -  bulgarian            europe/bg     
 5  bs             M  bosnian              europe/bs     
 ```

Older eSpeak does this instead: (a blank instead of a dash)
```
Pty Language Age/Gender VoiceName          File          Other Languages
 5  af             M  afrikaans            other/af      
 5  an             M  aragonese            europe/an     
 5  bg                bulgarian            europe/bg     
 5  bs             M  bosnian              europe/bs     
 ```

I didn't notice the mbrola section, yes, that should do fine.
The one catch I found is that for some unknown reason, eSpeak will sometimes list all the mbrola voices it knows of, and other times only the ones that are installed. So it listing a mbrola voice doesn't mean it is working.

The reason you'd want to detect languages is because you don't necessarily know the language up-front. e.g. For me, I have friends/family that will speak to me in Afrikaans (my mother tongue), and others that can't speak it, which communicates in English. Further more, for my wife, does lots of dealings with French Africa, and communicates in French often.

If we get a message, you can't determine the language of the message, without looking at the message contents. Hence the need to in some cases, have the ability to detect the language.

You can definitely make it an optional element, but would be a practical requirement for any person that is fluent in more than one language.
I mentioned langid, because it is pre-trained and already self-contained. You can also limit the detection range to a set of languages, so if you only understand 3 languages, you limit it to just those, and it will choose the closest language.

**Comment by Holzhaus** [comment]
> Older eSpeak does this instead: (a blank instead of a dash)

I browsed though the source and it seems like that has been changed in [commit r331](http://sourceforge.net/p/espeak/code/331/#diff-16) from March 23 2013. So that should be fixed if espeak is at least version 1.47.03b or newer. Even Debian stable has a newer version in its repos by now, so I'd not count on anyone still using such an old version. I think I'll go without a workaround for now and see if anyone complains.

> The one catch I found is that for some unknown reason, eSpeak will sometimes list all the mbrola voices it knows of, and other times only the ones that are installed. So it listing a mbrola voice doesn't mean it is working.

Ok, that's stupid. Do you know some way to determine if that voice is actually installed and usable?

> The reason you'd want to detect languages is because you don't necessarily know the language up-front. e.g. For me, I have friends/family that will speak to me in Afrikaans (my mother tongue), and others that can't speak it, which communicates in English. Further more, for my wife, does lots of dealings with French Africa, and communicates in French often.

Currently, a user has to choose a language in the config file, an Jasper will work in that language (it'll listen for speech in that language and answer in that language). While I think that you use-case is a bit special, I'd definitly consider adding it - but I've yet to think of a decent way of doing that.

I doesn't make much sense to talk to jasper in one language and get an answer in another one, so ideally, Jasper should answer in the same language you spoke your command in. So we need to determine which language your command is in - but we can't do that by guessing it from text rather than guessing it from the actual speech audio. And I've currently no idea how to do that reliably.

If we have some recorded audio data, we need to know its language BEFORE transcribing it (which we don't know in your use case). Alternatively, we could also transcribe it in all configured languages in parallel and compare the results - but how to decide, what transcription is the proper one? Because if you try to transcribe french speech with an english STT engine, it often will return some english text (the meaning may be nonsense, but how should Jasper know?).

So I see no way to implement you use case right now. If you have a decent idea, feel free to share it.

**Comment by grigi** [comment]
Ubuntu 12.04LTS has the old version, and that is the OS that is still used by Travis, so if you want to do CI tests using Travis, you will unfortunately have to support that workaround.

The only real use-case of multi-language would be when reading messages from email/twitter/etc... And then only if the user explicitly states being multi-lingual and then also explicitly configures each language.

I'll have to do more investigation as to why eSpeak often lists all supported mbrola voices and not just the supported & installed ones.
The work-around that I did was to look in the folders where eSpeak looks at:
/usr/share/espeak-data/mbrola then /usr/share/mbrola/ as mentioned in the documentation.
In pretty much all the distros I have tested, /usr/share/mbrola/ is where the voices install to.

When doing an strace, for mbrola-en1 you see eSpeak tends to try and open  /usr/share/espeak-data/mbrola/en1/en1 and then /usr/share/mbrola/en1/en1

So maybe just look for those files?

You can get the first path from eSpeak itself:
```
$ espeak --help
eSpeak text-to-speech: 1.47.11  03.May.13  Data at: /usr/share/espeak-data
```
The second I think is hardcoded.

**Comment by Holzhaus** [comment]
Multilanguage support is almost ready, the only 2 plugins missing are the MPDControl ("Music Mode") and the Hacker News plugin.

Hacker News isn't translatable, since the the website itself is english-only. I'm going to add mutlilanguage functionality for MPDControl soon. If that's done, I'd like to merge this branch into `jasper-dev`.

@shbhrsaha @crm416 Any comments?

**Comment by Holzhaus** [comment]
`MPDControl` plugin is also done.

**Pull request merged**
