### PR TITLE
Say it in another language (accent)

### PR DESCRIPTION
**Pull request by n3bojs4**
Add the option to say the phrase in another language. Two changes must be done here and in the tts engine class method.
I'll make a PR for the method say in class GoogleTTS

### CODE REVIEW

**Comment by Holzhaus** [comment]
This doesn't really make sense now, because now all TTS engines support setting the language and - more importantly - we currently have no means to translate the phrases. So everything would still be in English language, it's just that we output english text with a spanish/german/etc. TTS engine.

**Comment by n3bojs4** [comment]
Hmmm i used it with my translate module, if you want to say "j'aime développer en python" with a german accent it's awful ... i don't understand why it doesn't really make sense ?

**Comment by grigi** [comment]
As a multi-lingual, I would really love it if Jasper gets support for many languages.
One thing that can be done is take every text fragment, and run it through a language identifier library like https://github.com/saffsd/langid.py and then have a different TTS config for each regisitered language.
e.g. In the configuration you say we have n languages:
```yaml
lang:
  default_lang: en
  en:
    tts_engine: mary
    mary:
      server: 'mary.dfki.de'
      port: '59125'
      language: 'en_GB'
      voice: 'dfki-spike'
  af:
    tts_engine: espeak
    espeak:
      voice: 'af'
  fr:
    tts_engine: mary
    mary:
      server: 'mary.dfki.de'
      port: '59125'
      language: 'fr'
      voice: 'upmc-pierre'
```

You then set the language scope by:
```py
langid.set_languages(['en','af', 'fr'])
```
and do:
```py
langid.classify(fragment)
```
to choose the output (or default to 'en' on error)

This would allow you to at least have a reasonable solution to having Jasper read messages in different languages, even though the regular responses are all in English for now.

**Comment by Holzhaus** [comment]
Please have a look at #383.

**Pull request closed without merging**
