### PR TITLE
Add initial support for Ivona-TTS

### LINKED ISSUE #348: IVONA TTS voices
Hey,

It would require an internet connection but the IVONA voices available at http://www.ivona.com/ are also available via an API at https://www.ivona.com/us/for-business/speech-cloud/ 

Someone has even written a wrapper library (although it could do with a cleanup and getting rid of pygame) at http://zacharybears.com/pyvona/

I've been playing around with Google STT + Google Translate + IVONA multi-lingual voices and it's great. The Russian 'Maxim' voice is particularly good (so I'm told), much better than the Google voices. 

It might be worth looking at.

### PR DESCRIPTION
**Pull request by Holzhaus**
Initial support for Ivona Speech Cloud TTS by Amazon.

This resolves #348.

### CODE REVIEW

**Comment by shbhrsaha** [comment]
Great, will test this weekend and report back!

**Comment by Holzhaus** [comment]
Cool. A `profile.yml` example:

```yaml
tts_engine: ivona-tts
ivona-tts:
  # Keys can be obtained via:
  # https://www.ivona.com/us/account/speechcloud/creation/
  access_key: 'access_key'
  secret_key: 'secret_key'
  voice: 'Eric' # optional, default is 'Brian'
  region: 'eu-west' # optional, default is 'us-east'
  speech_rate: 'medium' # optional
  sentence_break: 400 #optional
```

**Comment by FreakErn** [comment]
`sudo apt-get install python-pymad`
`pip install pyvona`

Merged the ivona branch, added the example config of Holzhaus, changed the keys and the voice to "Salli" and it worked perfectly fine!

**Comment by Nathan-Ayling** [comment]
Awesome, I got to give this a try, will see how it goes.

**Comment by Nathan-Ayling** [comment]
Will have to give this a try! The current robotic voice isn't great.

**Comment by FreakErn** [comment]
yeah, i used a virtual environment, you should use sudo to get the permissions.
`sudo pip install pyvona`

**Comment by shbhrsaha** [comment]
Fantastic! Great work, Jan. Worked well for me with those instructions. This can be merged in with documentation.

Just an observation:
I had to uninstall pygame with `sudo apt-get remove python-pygame`. I also had to change:
https://github.com/jasperproject/jasper-client/blob/master/client/tts.py#L66
to read `cmd = ['aplay', '-D', 'plughw:1,0', str(filename)]`. ([Google TTS users reported a similar experience.](https://groups.google.com/forum/#!searchin/jasper-support-forum/Sample$20format$20non$20available/jasper-support-forum/5tmgNqv0i_A/mbXeybpmDXcJ)). After the change, espeak TTS continues to work.

Was this your experience? If so, that `cmd` definition adjustment might be a necessary change independent of this PR.

**Comment by Holzhaus** [comment]
> I had to uninstall pygame with sudo apt-get remove python-pygame.


Maybe because your installed pygame version was too old? Pyvona doesn't check the pygame version, only if it exists or not. What was the error?

> I also had to change:
> https://github.com/jasperproject/jasper-client/blob/master/client/tts.py#L66
> to read cmd = ['aplay', '-D', 'plughw:1,0', str(filename)]. (Google TTS users reported a similar experience.). After the change, espeak TTS continues to work.

Yup, plughw takes care of samplerate conversion and stuff like that (in case the device doesn't support it by hardware). Should be an issue if we changed that.

> Was this your experience?

Can't really say, since my audio setup is a bit different. I'm always patching that line to read `cmd = ['aplay', '-D', 'default', str(filename)]`. This change would be even better, so that users can device which device should be used by configuring their `~/.asoundrc`, but I don't think we can't change that without breaking their current setups.

**Comment by FreakErn** [comment]
i haven't installed pygame, so no idea about that.

My cmd line looks like
`cmd = ['aplay', str(filename)]` because i want to use the usb-audio output instead of using the raspi-low-volume output.

Maybe you can do this selectable during the profile configuration (populate.py)

**Comment by shbhrsaha** [comment]
Ah, OK. Thanks for sharing your experiences, @Holzhaus and @FreakErn. When I run with Pygame, the error is:

```
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/pi/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python module 'pocketsphinx' found: '/usr/local/lib/python2.7/dist-packages/pocketsphinx.so'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking python import 'mad'...
DEBUG:client.diagnose:Python module 'mad' found: '/usr/lib/pymodules/python2.7/madmodule.so'
DEBUG:client.diagnose:Checking python import 'pyvona'...
DEBUG:client.diagnose:Python module 'pyvona' found: '/usr/local/lib/python2.7/dist-packages/pyvona.py'
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 143, in <module>
    app = Jasper()
  File "jasper.py", line 105, in __init__
    self.mic = Mic(tts_engine_class.get_instance(),
  File "/home/pi/jasper-client/client/tts.py", line 58, in get_instance
    instance = cls(**config)
  File "/home/pi/jasper-client/client/tts.py", line 583, in __init__
    self._pyvonavoice = pyvona.Voice(access_key, secret_key)
  File "/usr/local/lib/python2.7/dist-packages/pyvona.py", line 234, in __init__
    pygame.mixer.init()
error: No available audio device
```

I think this PR should be good to merge for now.

Re: the separate issue of aplay parameters, I believe that @Holzhaus has implemented what @FreakErn is describing with https://github.com/jasperproject/jasper-client/pull/247, so thankfully this platform indepedence will be the standard soon.

**Comment by Holzhaus** [comment]
@shbhrsaha I filed an upstream patch over at zbears/pyvona#10 to avoid that behaviour.

**Comment by shbhrsaha** [comment]
Great idea. Thanks @Holzhaus

**Comment by Holzhaus** [comment]
My patch has been merged upstream, so I think this is safe to merge.

**Pull request merged**
