### PR TITLE
[WIP] New plugin system

### PR DESCRIPTION
**Pull request by Holzhaus**
**NOTE:** This is a work in progress and not ready for merging.

I don't want to say that ambition is the enemy of progress, but Jasper development has lately been a dragging along much slower than before. On my side, this is partly because I had all these cool ideas about a new architecture for Jasper (#280) , and that lead to me trying to do too much at once, which leads to a lot of problems and thus kills motivation.

This time I'll try smaller and more incremental changes and improvements to reach the overall goal.

So here's my take on a simple plugin system. It search in one or more folders and detects plugins there. Plugins consist of a python module containing a subclass of a plugin superclass (currently only `SpeechHandlerPlugin` exists, which replaces the modules in `client/modules`) and a `plugin.info` file that describes the plugin. I hardcoded that name to make sure that every plugin will be put into it's own subfolder.

This also has initial (currently non-working) support for translatable modules via [gettext](https://docs.python.org/2/library/gettext.html).

Some architectural changes were necessary to make this work, namely:
- Move phrase extraction functions out of `vocabcompiler` and into the `Brain` class (0bc3674)
- Only use `Brain` for querying, not for the handling itself (which is now done in `Conversation`) (0bc3674)

I also tried using [yapsy](http://yapsy.sourceforge.net/) (#130), which looked very good at first (and it really is), but it also has some concepts and limitations that are quite different from what I had in mind for Jasper, so I decided against using it as a base. This might look like the [NIH symdrome](https://en.wikipedia.org/wiki/Not_invented_here), but I already had a yapsy-based implementation counting more than 1k lines (this PR does look as big, but most of it is just moving code around - especially moving each plugin into its own folder). This is not only huge, but also has some very ugly workarounds for some problems that are related to how yapsy works.

**TODO:**
- [x] Fix testcases
- [x] Add more plugin types
- [x] Fix even more testcases
- [x] Get a drink
- [x] Add proper translations (gettext) support

@shbhrsaha @crm416 Any feedback yet?

### CODE REVIEW

**Comment by benhoff** [comment]
I don't know if it's what you're looking for, but I also had some problems with yapsy and am working on my own plugin system. It's not finished, but the nominal implementation looks something like this:

    from pluginmanager import Interface

    plugin_interface = Interface()
    plugin_interface.set_plugin_directories('my/fancy/plugin/path')
    plugin_interface.collect_plugins()
    plugin_interface.configure_plugins(dict_object_with_config_values)

    plugin_instances = plugin_interface.get_plugins()

https://github.com/benhoff/pluginmanager
The only problem being that it's written in Python 3...

**Comment by Holzhaus** [comment]
@crm416 @shbhrsaha Any comments so far? I know this looks huge, but it's a lot of moving code around and fixing testcases. I can split the commits regarding the plugin system from the commits migrating the actual STT/TTS engines and modules if that makes it easier for you to review.

**Comment by shbhrsaha** [comment]
Sorry for the late reply, @Holzhaus. I'm traveling at the moment but will take a close look at it this weekend. Excited about this feature proposal

**Comment by shbhrsaha** [comment]
Finally took a look! I love it. Since it's a lot of changes in progress, I didn't look closely at the changed lines, but my understanding is that you'd like to generalize "plugins" to include both text/speech engines and what we currently call "modules" that handle input, with the latter all falling under the speechhandler plugin. I think moving phrase extraction from vocabcompiler to brain makes sense. Putting command handling in Conversation is reasonable. I agree that creating a custom plugin system instead of adapting Yapsy will be simpler. Keep up the great work! Look forward to merging in the polished revision.

**Comment by Holzhaus** [comment]
OK, gettext support is ready. I verified this by translating the `clock` plugin (the former `time` module which had to be renamed to avoid clashes with the stdlib package) to german and it works fine. I'll merge this PR as-is into the `jasper-dev` branch keep the PR clean. The actual multilingual stuff will come as a seperate PR.

Please note that there could (and probably will) still be changes to the plugin API later on, but these will be in separate PRs. This one works and has already grown too big.

**Pull request merged**
