### PR TITLE
add multilanguage functionality

### PR DESCRIPTION
**Pull request by MakeMeASandwich**
With these patches it is possible to use Jasper with different languages.
Only the Time, Unclear, Joke (partial) and Life plugins are translated yet.

---

I wanted to use Jasper in German, so I did the following on my Arch Linux laptop:
- Set up Jasper
- Make sure everything works in English. I needed to change `aplay -D hw:1,0 str(filename)` to `aplay str(filename)` in client/stt.py
- Get the language model, I got mine from [here](http://goofy.zamia.org/voxforge/de/).
- In my case, the fst was in `phonetisaurus/dict-xsampa.fst` and the hmm_dir was `voxforge-de-r20141117/model_parameters/voxforge.cd_cont_3000`. After some fiddeling I realized that there are different formats, `ARPA` and `XSAMPA`. pocketsphinx needs `ARPA`, but my model was `XSAMPA` - luckily there [is a script](https://github.com/gooofy/voxforge) to convert inbetween them. I changed a regular expression, added an option for the conversion and included this script. You need to add the line `fst_ist_xsampa: true` below the line with `fst_model` in your `profile.yml`.
- Now the keywords need to be changed. gettext does this, I added a draft translation. To convert it, go to Jasper's root folder and execute `msgfmt messages.po`. The phonetized words seem to be cached in `~/.jasper/vocabularies`, so you should flush it with `rm -rf ~/.jasper/vocabularies`.
- Next, configure espeak to speak in the right language, that is `voice: 'german'` in the profile.yml.
- I did not really like the espeak voice so I wanted to try PicoTTS instead. It turns out that the Pkgbuild is not working anymore because the source repository has been taken down (DMCA). [PicoPi](https://github.com/DougGore/picopi) worked fine for me:
  - Download, compile, install
  - Change `pico/tts/main.cpp` and replace the path `ttsEngine->init(synth_done, '../lang')` to the absolute path to the `lang` directory, because otherwise you need to be in the `tts` directory when running `./testtts`.
  - Compile again and add PicoPiTTS to `client/tts.py`. [Here](https://gist.github.com/MakeMeASandwich/cb284bae65f8b7870942) is a gist, it's hacky and insecure but works.

### CODE REVIEW

**Comment by frostworx** [comment]
today I wanted to try jasper and the first thing I looked for after initial setup is an option to switch languages.
you obviously put a lot of work into your pullrequest, so thank you very much for it!
I hope it gets the attention which it deserves and gets merged into master soon.
I collected the datafiles you linked above, configured them, applied the patches without patches, but for some unknown reason I receive a 
===
  File "jasper.py", line 93, in __init__
    _langs = gettext.translation('messages', localedir='./languages', languages=LANGUAGES)
  File "/usr/lib64/python2.7/gettext.py", line 469, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'messages
===
the same also happens with a fresh clone of your fork.
running with --debug arg doesn't give more hints.

a test.py with
import locale
print locale.getdefaultlocale()
returns a
('de_DE', 'UTF-8')
so this can't be the problem.
I'm running gentoo btw which uses a python-wrapper to allow easy switching between python versions.
never ever had any problem with it though.
any hint what could be wrong is very welcome!

**Comment by frostworx** [comment]
almost forgot.
in case someone else has the same "problem"
you have to convert the gettext po file to a mo file using msgfmt
in order to make it recognized.

**Comment by sapier** [comment]
Could you please add more information about how to convert the xsampa dictionary to arpa? I did follow your instructions but didn't find out which script to use. As you had a commit which looked like fixing the issue whithout conversion I tried anyway. Yet I have zero recognition rate. English version works fine so it's most likely not a audio issue.
Thanks!

**Comment by MakeMeASandwich** [comment]
@frostworx Thanks for the pointer, I'll add this to the list above.

@sapier I built this months ago… I already uninstalled Jasper's dependencies, and rebuilding takes so long :-/ I might try it again this weekend in a virtual machine.
Regarding zero recognition: Check whether your mic is active and the volume (Seriously, I wasted hours on this 'bug'). Then check whether the dictionaries `~/.jasper/vocabularies/pocketsphinx-vocabulary/default/dictionary` `~/.jasper/vocabularies/pocketsphinx-vocabulary/keyword/default` contain actual data. Also there is a `sh` script to test the pocketsphinx model in the voxforge folder, I do not remember any details about it but you can use it to test further.

**Comment by sapier** [comment]
yes I added fst_is_xsampa: true
Is dictionary supposed to look like this?
https://gist.github.com/sapier/5bef14dd1fa75bf1d086

Sadly I can't use the pocketsphinx test script as it tries to open my audio device (cirrus audio) in a unsupported mode and immediatly failes.
On the other hand jasper using enlish language works fine (despite of me not wanting to talk english to a german flat ;-)) So I guess audio config for jasper ain't the problem.

**Comment by MakeMeASandwich** [comment]
> EDIT: well I had "fst_is_xsampa: True" seems like this is very important for python it works wai better now.

Oh sorry, that was a typo. My fault.
Does that mean you were successful? Or does it still not work?

**Comment by Holzhaus** [comment]
I'm currently adding multilanguage support in PR #383 (along with some german translations).

This does not include X-SAMPA support, which could be added in a seperate PR. Since Jasper is MIT-licensed and that conversion script is GPL, I'm unsure if we can use it. I'll have to look into this when I have the time.

**Comment by MakeMeASandwich** [comment]
> I'm currently adding multilanguage support in PR #383 (along with some german translations).

That's great!
This PR wasn't meant to be merged, after all. It's more a how-to guide.

About the license… I'm sure you could contact the author and ask for permission and he'll grant it.
Otherwise, it looks so simple that one could write it by him/herself.

**Comment by Holzhaus** [comment]
> Otherwise, it looks so simple that one could write it by him/herself.

Strictly speakting, now that I have seen the script, I'm "tainted" by GPL code and can't implement this under MIT license anymore.

I'll ask the original dev.

**Pull request closed without merging**
