### PR TITLE
Added basic Julius STT engine and vocabcompiler

### PR DESCRIPTION
**Pull request by Holzhaus**
This adds a STT/Vocabulary implementation for the [Open-Source Large Vocabulary CSR Engine Julius](http://julius.sourceforge.jp/en_index.php) to Jasper.

Basically, recognition is working, but the freely available speaker-independent acoustic models offer a recognition rate that is probably too bad to use without custom training.

We COULD include this and state in the documentation that you need a custom trained acoustic model (you can define it via `profile`) and that we do not provide support for this step (and link to [this tutorial](http://www.voxforge.org/home/dev/acousticmodels/linux/adapt/htkjulius)).

@crm416 @shbhrsaha Do we want to merge this in on the above conditions?

### CODE REVIEW

**Comment by shbhrsaha** [comment]
Yup, sounds good to give people the option. I support

**Comment by Holzhaus** [comment]
I added documentation for this [here](https://github.com/jasperproject/jasperproject.github.io/pull/31).

**Comment by shbhrsaha** [comment]
Not going to test this on the Pi, but I trust this worked for you on Arch so good to merge in

**Comment by andweber** [comment]
I tried the julius plugin and couldn't get it running out of the box. 
It seems like the function definition of compile_vocabulary is not correct. That's why the profile options 
"lexicon" and "lexicon_archive_member" are not recognized. I made a patch.

[fix_def_julius_compile_vocabulary_patch.txt](https://github.com/jasperproject/jasper-client/files/168131/fix_def_julius_compile_vocabulary_patch.txt)

Fixing this I'm stuck with the following error:

>
INFO:jasper.vocabcompiler:Starting compilation...
ERROR:jasper.vocabcompiler:Fatal compilation error occured
Traceback (most recent call last):
  File "./jasper/vocabcompiler.py", line 140, in compile
    compilation_func(config, self.path, phrases)
  File "./plugins/stt/julius-stt/juliusvocab.py", line 133, in compile_vocabulary
    subprocess.call(cmd, stdout=out_f, stderr=out_f)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

It seems like it is tried to call "mkdfa.pl".  Is it missing??

**Comment by andweber** [comment]
one more issue. "Jasper" as default keyword is dropped when compared with the dictionary because comparison is case sensitive. 

I added two ways of fixing this:
1. always lookup with uppercase in translate_word
2. making sure that the keyword is always uppercase 
choose the best one.

[fix_def_julius_compile_vocabulary_patch_3.txt](https://github.com/jasperproject/jasper-client/files/170127/fix_def_julius_compile_vocabulary_patch_3.txt)

**Comment by Renezera** [comment]
Hey guys, I'm very new to all this and I'm having trouble setting up Julius-STT. Is there any step-by-step guide out there that can help me? Or is there any other STT that works better than the sphinx? I have some accent and sphinx doesn't recognizes 40% of the words I say lol.
Thanks again!

**Pull request merged**
